todotasks/apps/tasks/urls.py
from django.conf.urls.defaults import *
from apps.tasks.forms import TaskForm
from apps.tasks.models import Task, Project

urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.list_detail.object_list',
       {'queryset':Project.objects.all().order_by('-created'),}, name='list-tasks'),

    url(r'^create/$', 'apps.tasks.views.create_tasks', {}, name='create-task'),

    url(r'^project/(?P<slug>[a-z\-0-9]+)$', 'django.views.generic.list_detail.object_detail',
       {'queryset':Project.objects.all(), 'slug_field':'title_slug',},name='read-project'),

    url(r'^task/(?P<slug>[a-z\-0-9]+)$', 'django.views.generic.list_detail.object_detail',
       {'queryset':Task.objects.all(), 'slug_field':'title_slug',},name='read-task'),

    url(r'^task/delete/(?P<object_id>\d+)$', 'django.views.generic.create_update.delete_object',
       {'model':Task,'post_delete_redirect':'/', 'login_required':True}, name='delete-task'),

    (r'^task/done/(?P<object_id>\d+)$', 'apps.tasks.views.mark_as_done'),
    )

todotasks/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import settings

admin.autodiscover()

urlpatterns = patterns('',
                       # Example:
                       # (r'^todotasks/', include('todotasks.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       (r'^admin/', include(admin.site.urls)),

                       (r'^', include('apps.tasks.urls')),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='log-in'),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
                           {'next_page':'/', 'redirect_field_name':'next',}, name='log-out'),
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT,
                                })
                            )

todotasks/apps/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.fields import AutoSlugField, AutoSlugField
from django_extensions.db.models import TimeStampedModel

# Create your models here.

class Project(TimeStampedModel):
    """
    A project contains a list of tasks to achieve.
    """
    title = models.CharField(max_length=42)
    title_slug = AutoSlugField(populate_from='title')
    description = models.TextField()

    def __unicode__(self):
        return self.title


class Task(TimeStampedModel):
    """
    A task is a sub part of a project.
    """
    title = models.CharField(max_length=42)
    title_slug = AutoSlugField(populate_from='title')
    description = models.TextField()
    created_by = models.ForeignKey(User)
    is_finished = models.BooleanField(default=False)
    project = models.ForeignKey(Project)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('read-task', (), {'slug':self.title_slug,})

todotasks/apps/tasks/forms.py
from django.forms.models import ModelForm
from apps.tasks.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = ('created_by', 'is_finished',)

todotasks/apps/tasks/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from apps.tasks.forms import TaskForm
from apps.tasks.models import Task

@login_required
def create_tasks(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.created_by = request.user
            task.save()
            return HttpResponseRedirect(reverse('read-project', args=(task.project.title_slug,)))
    else:
        form = TaskForm()
    params = {'form':form, 'user': request.user }
    params.update(csrf(request))
    return render_to_response('tasks/task_form.html', params)

@login_required
def mark_as_done(request, object_id):
    task = get_object_or_404(Task, id=object_id)
    if not task.is_finished:
        task.is_finished = True
        task.save()
    return HttpResponseRedirect(reverse('read-project', args=(task.project.title_slug,)))

todotasks/templates/menu.html
<div id="menu" class="span-4">
    <a href="{% url list-tasks %}">View tasks.</a><br />
    {% if not user.is_authenticated %}
        <a href="{% url log-in %}?next={{ request.path }}">Log in.</a><br />
    {% else %}
        <a href="{% url create-task %}">Create a task.</a><br />
        <a href="{% url log-out %}?next_page=/">Log out.</a>
    {% endif %}
</div>

todotasks/templates/struct.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >
<head>
    <title>{% block head-title %}{% endblock head-title %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% block head-css %}
        <link rel="stylesheet" media="screen" type="text/css" title="Design" href="/css/design.css" />
        <link rel="stylesheet" href="/css/blueprint/screen.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="/css/blueprint/print.css" type="text/css" media="print" />
        <!--[if lt IE 8]>
            <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection" />
        <![endif]-->
        <link type="text/css" href="/css/start/jquery-ui-1.8.9.custom.css" rel="Stylesheet" />

    {% endblock head-css %}
    {% block head-js %}
        <script type="text/javascript" src="/js/jquery-1.4.4.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.8.9.custom.min.js"></script>
    {% endblock head-js %}
    {% block head-rss %}{% endblock head-rss %}
</head>
<body>
<div class="container">
    <div id="header" class="span-24 last">
        {% block header-title %}{% endblock header-title %}
    </div>
    {% include 'menu.html' %}
    <div id="body" class="span-16 last">{% block body %}{% endblock body %}</div>
    <div id="footer" class="span-24 last">some footer informations of your choice.</div>
</div>
</body>
</html>

todotasks/templates/tasks/project_detail.html
{% extends 'struct.html' %}
{% block title %}Project detail{% endblock title %}
{% block header-title %}
    Project-detail
{% endblock header-title %}
{% block body %}
    <h1>{{ object.title }}</h1>
    <div>{{ object.description|truncatewords:20 }}</div>
    {% for task in object.task_set.all %}
        <div class="{% if task.is_finished %}finished{% else %}not-finished{% endif %}">
            <h2>{{ task.title }}</h2>
            <p><a href='{% url read-task task.title_slug %}'>See details</a></p>
            <div>{{ task.description }}</div>
        </div>
    {% endfor %}
{% endblock body %}

todotasks/templates/tasks/project_list.html
{% extends 'struct.html' %}
{% block title %}Index{% endblock title %}
{% block header-title %}
    Index
{% endblock header-title %}
{% block head-js %}
    {{ block.super }}
    <script type="text/javascript" src="/js/tasks/project_list.js"></script>
{% endblock head-js %}
{% block body %}
    <div id="accordion" class="ui-accordion ui-widget ui-helper-reset">
        {% for project in object_list %}
            <h3 class="ui-accordion-header ui-helper-reset ui-state-active ui-corner-top">
                <a href="#">{{ project.title }}</a>
            </h3>
            <div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active">
                <p><a href='{% url read-project slug=project.title_slug %}'>See details</a></p>
                <div>{{ project.description|truncatewords:20 }}</div>
                {% for task in project.task_set.all %}
                    <div class="{% if task.is_finished %}finished{% else %}not-finished{% endif %} task">
                        <h2>{{ task.title }}</h2>
                        <div>{{ task.description }}</div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock body %}

todotasks/templates/tasks/task_confirm_delete.html
{% extends 'struct.html' %}
{% block title %}Remove task{% endblock title %}
{% block header-title %}
    Remove Task
{% endblock header-title %}
{% block body %}
    <h1>{{ object.title }}</h1>
    <div>
        {{ object.description }}
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <p>Do you really want to remove it ?</p>
        <input type="submit" value="Yes!"/>
    </form>
{% endblock body %}

todotasks/templates/tasks/task_detail.html
{% extends 'struct.html' %}
{% block title %}Task detail{% endblock title %}
{% block header-title %}
    Task-detail
{% endblock header-title %}
{% block body %}
    <h1>{{ object.title }}</h1>
    <div>
    {{ object.description }}
    </div>
    <div>Actions : <a href='{% url delete-task object.id %}'>remove it.</a><br />
    <a href='{% url apps.tasks.views.mark_as_done object.id %}'>mark it a done!</a></div>
{% endblock body %}

todotasks/templates/tasks/task_form.html
{% extends 'struct.html' %}
{% block title %}Create a task{% endblock title %}
{% block header-title %}
    Create a task
{% endblock header-title %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
{% endblock body %}

todotasks/templates/tasks/task_list.html
{% extends 'struct.html' %}
{% block title %}Index{% endblock title %}
{% block header-title %}
    Index
{% endblock header-title %}
{% block body %}
    {% for task in object_list %}
        <div class="{% if task.is_finished %}finished{% else %}not-finished{% endif %}">
            <h1>{{ task.title }}</h1>
            <div>{{ task.description|truncatewords:20 }}</div>
            <p><a href="{% url read-task task.title_slug %}">see more...</a></p>
        </div>
    {% endfor %}
{% endblock body %}